brew "awscli"
brew "ghq"
brew "git"
brew "go"
brew "jq"
brew "mise"
brew "peco"
brew "sheldon"
brew "tmux"
brew "neovim"
cask "1password-cli"
cask "font-hackgen" # https://github.com/yuru7/HackGen
cask "font-hackgen-nerd"
