tap "homebrew/bundle"
brew "ffmpeg"
brew "ghq"
brew "gpg" # asdf-nodejs depends on
brew "git"
brew "go"
brew "jq"
brew "peco"
brew "reattach-to-user-namespace"
brew "rust"
brew "sheldon"
brew "the_platinum_searcher"
brew "tmux"
brew "macvim"
cask "font-hackgen" # https://github.com/yuru7/HackGen
cask "font-hackgen-nerd"
