# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
# upgrade

# Add Repository
tap phinze/homebrew-cask

# Packages
install brew-cask || true
install git || true
install hg || true
install zsh || true
install go || true
install tmux || true
install rbenv || true


# .dmg
cask install google-chrome || true
cask install firefox || true
cask install virtualbox || true
cask install vagrant || true
cask install dropbox || true
cask install skype || true
cask install alfred || true
cask install kobito || true
cask install iterm2 || true
cask install soundflower || true
cask install appcleaner || true
cask install amazon-cloud-player || upgrade amazon-cloud-player || true
cask install bettertouchtool || upgrade bettertouchtool || true
cask install processing || upgrade processing || true
cask install google-japanese-ime || upgrade google-japanese-ime || true

# link
brew cask alfred link

# Remove outdated versions from the cellar
cleanup
