# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
# upgrade

# Add Repository
tap homebrew/versions
tap phinze/homebrew-cask
tap sanemat/font

# Packages
install brew-cask || true
install git || true
install hg || true
install zsh || true
install go || true
install tmux || true
install rbenv || true
install ruby-build || true
install readline || true
install ricty || true
install heroku-toolbelt
install z


# .dmg
cask install google-chrome || true
cask install firefox || true
cask install virtualbox || true
cask install vagrant || true
cask install dropbox || true
cask install skype || true
cask install alfred || true
cask install kobito || true
cask install iterm2 || true
cask install appcleaner || true
cask install java || true
cask install mplayerx || true
cask install soundflower || true
cask install supercollider || true
cask install processing || upgrade processing || true
cask install amazon-cloud-player || upgrade amazon-cloud-player || true
cask install bettertouchtool || upgrade bettertouchtool || true
cask install google-japanese-ime || upgrade google-japanese-ime || true


# Remove outdated versions from the cellar
cleanup
